version: '3.8'

services:
  # Baza Podataka
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: planner_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # Backend (Python Flask/FastAPI)
  backend:
    build: ./backend
    container_name: python_backend
    restart: always
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/planner_db
    depends_on:
      - db

  # Frontend (React)
  frontend:
    build: ./frontend/planner
    container_name: react_frontend
    ports:
      - "5173:5173"
    stdin_open: true
    depends_on:
      - backend
